<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <EnableConfigurationBindingGenerator>true</EnableConfigurationBindingGenerator>
    <PublishAot Condition="'$(EnableAotPublishing)' == 'true'">true</PublishAot>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Npgsql" />
    <PackageReference Include="graft.nuget.ordering.api_bxfi5d" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\eShop.ServiceDefaults\eShop.ServiceDefaults.csproj" />
    <Compile Include="..\Shared\GraftRabbit.cs" Link="GraftRabbit.cs" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Application.UnitTests" />
  </ItemGroup>
</Project>
